package com.mart.model;

// Generated Aug 12, 2014 10:36:52 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import com.mart.annotation.POSFieldAnnotation;
import com.mart.annotation.POSModelAnnotation;

/**
 * InventoryItem generated by hbm2java
 */
@POSModelAnnotation(dbTableName="INVENTORY_ITEM")
public class InventoryItem extends POSModel implements java.io.Serializable {

	@POSFieldAnnotation(dbColumnName = "id", jsonColumnName = "id")
	private Integer id;

	@POSFieldAnnotation(dbColumnName = "product_id", jsonColumnName = "product_id")
	private Integer productId;

	@POSFieldAnnotation(dbColumnName = "name", jsonColumnName = "name")
	private String name;
	
	@POSFieldAnnotation(dbColumnName = "tracking_code", jsonColumnName = "tracking_code")
	private String trackingCode;
	
	@POSFieldAnnotation(dbColumnName = "quantity", jsonColumnName = "quantity")
	private int quantity;

	@POSFieldAnnotation(dbColumnName = "received_date", jsonColumnName = "received_date")
	private Date receivedDate;

	@POSFieldAnnotation(dbColumnName = "expiry_date", jsonColumnName = "expiry_date")
	private Date expiryDate;
	
	@POSFieldAnnotation(dbColumnName = "promotional_offer", jsonColumnName = "promotional_offer")
	private String promotionalOffer;

	/**
	 * @return the id
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * @param id the id to set
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * @return the productId
	 */
	public Integer getProductId() {
		return productId;
	}

	/**
	 * @param productId the productId to set
	 */
	public void setProductId(Integer productId) {
		this.productId = productId;
	}

	/**
	 * @return the name
	 */
	public String getName() {
		return name;
	}

	/**
	 * @param name the name to set
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * @return the trackingCode
	 */
	public String getTrackingCode() {
		return trackingCode;
	}

	/**
	 * @param trackingCode the trackingCode to set
	 */
	public void setTrackingCode(String trackingCode) {
		this.trackingCode = trackingCode;
	}

	/**
	 * @return the quantity
	 */
	public int getQuantity() {
		return quantity;
	}

	/**
	 * @param quantity the quantity to set
	 */
	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	/**
	 * @return the receivedDate
	 */
	public Date getReceivedDate() {
		return receivedDate;
	}

	/**
	 * @param receivedDate the receivedDate to set
	 */
	public void setReceivedDate(Date receivedDate) {
		this.receivedDate = receivedDate;
	}

	/**
	 * @return the expiryDate
	 */
	public Date getExpiryDate() {
		return expiryDate;
	}

	/**
	 * @param expiryDate the expiryDate to set
	 */
	public void setExpiryDate(Date expiryDate) {
		this.expiryDate = expiryDate;
	}

	/**
	 * @return the promotionalOffer
	 */
	public String getPromotionalOffer() {
		return promotionalOffer;
	}

	/**
	 * @param promotionalOffer the promotionalOffer to set
	 */
	public void setPromotionalOffer(String promotionalOffer) {
		this.promotionalOffer = promotionalOffer;
	}

	/**
	 * 
	 */
	public InventoryItem() {
		super();
		// TODO Auto-generated constructor stub
	}

	
}
