package com.mart.model;

// Generated Aug 12, 2014 10:36:52 PM by Hibernate Tools 3.4.0.CR1

import com.mart.annotation.POSFieldAnnotation;
import com.mart.annotation.POSModelAnnotation;

/**
 * Manufacturer generated by hbm2java
 */
@POSModelAnnotation(dbTableName="MANUFACTURER")
public class Manufacturer extends POSModel implements java.io.Serializable {

	@POSFieldAnnotation(dbColumnName = "id", jsonColumnName = "id")
	private Integer id;

	@POSFieldAnnotation(dbColumnName = "name", jsonColumnName = "name")
	private String name;

	/**
	 * @return the id
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * @param id the id to set
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * @return the name
	 */
	public String getName() {
		return name;
	}

	/**
	 * @param name the name to set
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * 
	 */
	public Manufacturer() {
		super();
		// TODO Auto-generated constructor stub
	}
	


}
